name: npm-publish

on:
  push:
    tags:        # only runs when you push a tag that matches the version
      - 'v*'     # e.g. v0.1.1
    branches:
      - main     # lets you trigger manually with workflow_dispatch if needed
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - run: npm ci

      - run: npm run build

      # Skip if the version already exists
      - name: Check if version exists
        id: check
        run: |
          PKG=$(node -p "require('./package.json').name")
          VER=$(node -p "require('./package.json').version")
          if npm view "$PKG@$VER" version > /dev/null 2>&1; then
            echo "exists=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Publish
        if: steps.check.outputs.exists != 'true'
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} 